services:
  db:
    image: postgres:11.4
    container_name: db-character
    ports:
      - "5434:5432"
    env_file:
      - .env
    volumes:
      - psql:/var/lib/postgresql/data/
    environment:
      - PGTZ=America/Argentina/Buenos_Aires
    networks:
      - character

  character:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: api-character
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - character
    depends_on:
      - db

networks:
  character:
    name: character
    external: true

volumes:
  psql:
    driver: local